### ISSUE TITLE
$this->redis->expireat not being called

### ISSUE THREAD

**Issue by lukestokes** [perimeter/rate-limiter-php#2]
If I replace `if ($rates[0] === $numTokens) {` with `if ((int)$rates[0] === (int)$numTokens) {` it works.

Not sure if I'm doing something wrong, but $rates[0] comes back as a string:
`PHP E_USER_NOTICE rate 0: s:1:"2";`

**Comment by n3vrax** [comment]
Hi,

Thanks for this good piece of code, I'm gonna use it in some zf2 project.

Sadly, this issue seems not to be closed. The problem is in the Throttler class, as @lukestokes said

line 61 on the RedisThrottler class

`
if ($rates[0] === $numTokens) 
`
should be 
`
if ((int)$rates[0] === $numTokens) 
`
Thanks again, I hope you'll fix this small bug, hate to have my dependencies manually edited :-p

**Comment by bshaffer** [comment]
this has been fixed
